  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gke-react
  name: gke-react
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-react
  template:
    metadata:
      labels:
        app: gke-react
    spec:
      containers:
        - name: gke-react
          image: gcr.io/trainingmodule-285008/gke-react
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gke-react
  name: gke-react
spec:
  ports:
  - nodePort: 30301
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gke-react
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: gcr.io/trainingmodule-285008/react-books-front
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: gke-react
          servicePort: 80



