steps:
  # build the container images
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/react-books-front", "./app/frontend"]
  # push the container image to gcloud registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/react-books-front"]

  # build the container images
  - name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/react-books-back", "./app/backend"]
  # push the container image to gcloud registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/react-books-back"]

#- name: 'gcr.io/cloud-builders/kubectl'
#  args:
#  - 'apply'
#  - '-f'
#  - 'app/kubeconfig.yaml'
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
