apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gke-react-back
  name: gke-react-back
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-react-back
  template:
    metadata:
      labels:
        app: gke-react-back
    spec:
      containers:
        - name: gke-react
          image: gcr.io/trainingmodule-285008/react-books-back
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gke-react-back
  name: gke-react-back
spec:
  ports:
  - nodePort: 30305
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: gke-react-back
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: gke-react-back
          servicePort: 80
